// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/signalfx/veneur/tdigest/tdigest.proto

package tdigest

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// MergingDigestData contains all fields necessary to generate a MergingDigest.
// This type should generally just be used when serializing MergingDigest's,
// and doesn't have much of a purpose on its own.
type MergingDigestData struct {
	// Use values rather than pointers for the Centroid array.  This avoids
	// a ton of code changes and probably a lot of allocations as well.
	MainCentroids        []Centroid `protobuf:"bytes,1,rep,name=main_centroids,json=mainCentroids,proto3" json:"main_centroids"`
	Compression          float64    `protobuf:"fixed64,2,opt,name=compression,proto3" json:"compression,omitempty"`
	Min                  float64    `protobuf:"fixed64,3,opt,name=min,proto3" json:"min,omitempty"`
	Max                  float64    `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	ReciprocalSum        float64    `protobuf:"fixed64,5,opt,name=reciprocalSum,proto3" json:"reciprocalSum,omitempty"`
	Debug                bool       `protobuf:"varint,6,opt,name=debug,proto3" json:"debug,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MergingDigestData) Reset()         { *m = MergingDigestData{} }
func (m *MergingDigestData) String() string { return proto.CompactTextString(m) }
func (*MergingDigestData) ProtoMessage()    {}
func (*MergingDigestData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02668dfd3875a22, []int{0}
}
func (m *MergingDigestData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MergingDigestData.Unmarshal(m, b)
}
func (m *MergingDigestData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MergingDigestData.Marshal(b, m, deterministic)
}
func (m *MergingDigestData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MergingDigestData.Merge(m, src)
}
func (m *MergingDigestData) XXX_Size() int {
	return xxx_messageInfo_MergingDigestData.Size(m)
}
func (m *MergingDigestData) XXX_DiscardUnknown() {
	xxx_messageInfo_MergingDigestData.DiscardUnknown(m)
}

var xxx_messageInfo_MergingDigestData proto.InternalMessageInfo

func (m *MergingDigestData) GetMainCentroids() []Centroid {
	if m != nil {
		return m.MainCentroids
	}
	return nil
}

func (m *MergingDigestData) GetCompression() float64 {
	if m != nil {
		return m.Compression
	}
	return 0
}

func (m *MergingDigestData) GetMin() float64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *MergingDigestData) GetMax() float64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *MergingDigestData) GetReciprocalSum() float64 {
	if m != nil {
		return m.ReciprocalSum
	}
	return 0
}

func (m *MergingDigestData) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

type Centroid struct {
	Mean                 float64  `protobuf:"fixed64,1,opt,name=mean,proto3" json:"mean,omitempty"`
	Weight               float64  `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Centroid) Reset()         { *m = Centroid{} }
func (m *Centroid) String() string { return proto.CompactTextString(m) }
func (*Centroid) ProtoMessage()    {}
func (*Centroid) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02668dfd3875a22, []int{1}
}
func (m *Centroid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Centroid.Unmarshal(m, b)
}
func (m *Centroid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Centroid.Marshal(b, m, deterministic)
}
func (m *Centroid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Centroid.Merge(m, src)
}
func (m *Centroid) XXX_Size() int {
	return xxx_messageInfo_Centroid.Size(m)
}
func (m *Centroid) XXX_DiscardUnknown() {
	xxx_messageInfo_Centroid.DiscardUnknown(m)
}

var xxx_messageInfo_Centroid proto.InternalMessageInfo

func (m *Centroid) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Centroid) GetWeight() float64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func init() {
	proto.RegisterType((*MergingDigestData)(nil), "tdigest.MergingDigestData")
	proto.RegisterType((*Centroid)(nil), "tdigest.Centroid")
}

func init() {
	proto.RegisterFile("github.com/signalfx/veneur/tdigest/tdigest.proto", fileDescriptor_d02668dfd3875a22)
}

var fileDescriptor_d02668dfd3875a22 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x31, 0x4d, 0x43, 0xe5, 0xaa, 0x88, 0x5a, 0x08, 0x59, 0x2c, 0x44, 0x15, 0x43, 0x16,
	0x12, 0x04, 0x12, 0x23, 0x03, 0x74, 0x65, 0x09, 0x1f, 0x80, 0x9c, 0xc4, 0x75, 0x9f, 0x54, 0xdb,
	0x91, 0xed, 0x40, 0x3e, 0x91, 0x1f, 0x60, 0xe5, 0x5b, 0x50, 0x5f, 0x1d, 0xa9, 0x4c, 0xbe, 0xf7,
	0x5c, 0x5f, 0xfb, 0xe9, 0xd1, 0x7b, 0x05, 0x61, 0xdb, 0xd7, 0x45, 0x63, 0x75, 0xe9, 0x41, 0x19,
	0xb1, 0xdb, 0x0c, 0xe5, 0xa7, 0x34, 0xb2, 0x77, 0x65, 0x68, 0x41, 0x49, 0x1f, 0xc6, 0xb3, 0xe8,
	0x9c, 0x0d, 0x96, 0x9d, 0x45, 0x7b, 0x7d, 0x77, 0x54, 0x55, 0x56, 0xd9, 0x12, 0xf3, 0xba, 0xdf,
	0xa0, 0x43, 0x83, 0xea, 0xd0, 0x5b, 0xfd, 0x10, 0xba, 0x7c, 0x93, 0x4e, 0x81, 0x51, 0x6b, 0x7c,
	0x60, 0x2d, 0x82, 0x60, 0xcf, 0xf4, 0x5c, 0x0b, 0x30, 0x1f, 0x8d, 0x34, 0xc1, 0x59, 0x68, 0x3d,
	0x27, 0xd9, 0x24, 0x9f, 0x3f, 0x2c, 0x8b, 0xf1, 0xd7, 0xd7, 0x98, 0xbc, 0x24, 0xdf, 0xbf, 0x37,
	0x27, 0xd5, 0x62, 0x7f, 0x7d, 0x64, 0x9e, 0x65, 0x74, 0xde, 0x58, 0xdd, 0x39, 0xe9, 0x3d, 0x58,
	0xc3, 0x4f, 0x33, 0x92, 0x93, 0xea, 0x18, 0xb1, 0x0b, 0x3a, 0xd1, 0x60, 0xf8, 0x04, 0x93, 0xbd,
	0x44, 0x22, 0x06, 0x9e, 0x44, 0x22, 0x06, 0x76, 0x4b, 0x17, 0x4e, 0x36, 0xd0, 0x39, 0xdb, 0x88,
	0xdd, 0x7b, 0xaf, 0xf9, 0x14, 0xb3, 0xff, 0x90, 0x5d, 0xd2, 0x69, 0x2b, 0xeb, 0x5e, 0xf1, 0x34,
	0x23, 0xf9, 0xac, 0x3a, 0x98, 0xd5, 0x13, 0x9d, 0x8d, 0xe3, 0x30, 0x46, 0x13, 0x2d, 0x85, 0xe1,
	0x04, 0xeb, 0xa8, 0xd9, 0x15, 0x4d, 0xbf, 0x24, 0xa8, 0x6d, 0x88, 0xc3, 0x45, 0x57, 0xa7, 0xb8,
	0x96, 0xc7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x1d, 0x82, 0xa2, 0x82, 0x01, 0x00, 0x00,
}
